### ISSUE TITLE
Usage on NPM with webpack

### ISSUE THREAD

**Issue by joshlasdin** [cloudinary/pkg-cloudinary-jquery-file-upload#1]
Maybe I'm missing something, but this package doesn't seem to come with any of the required dependencies needed to actually use it. When trying to bundle it into my project I get errors like:

```
ERROR in ./~/cloudinary-jquery-file-upload/cloudinary-jquery-file-upload.js
Module not found: Error: Cannot resolve module 'transformation' in /project/node_modules/cloudinary-jquery-file-upload
 @ ./~/cloudinary-jquery-file-upload/cloudinary-jquery-file-upload.js 657:13-80

ERROR in ./~/cloudinary-jquery-file-upload/cloudinary-jquery-file-upload.js
Module not found: Error: Cannot resolve module 'tags/imagetag' in /project/node_modules/cloudinary-jquery-file-upload
 @ ./~/cloudinary-jquery-file-upload/cloudinary-jquery-file-upload.js 2177:13-155

ERROR in ./~/cloudinary/lib/uploader.js
Module not found: Error: Cannot resolve module 'fs' in /project/node_modules/cloudinary/lib
 @ ./~/cloudinary/lib/uploader.js 15:7-20
```

I noticed that there are dependencies listed in the bower.json, any way there's a documented work-around for using with NPM?

**Comment by dfguo** [comment]
+1 
i got this error too

**Comment by michaek** [comment]
This module is not designed to be compatible with webpack, as it expects its in a node environment because module.exports is an object. I was able to load the module in webpack with  https://github.com/webpack/script-loader .

The dependencies are not built into the file, and i needed to do something like:

```
import "script!jquery"
import "script!blueimp-file-upload/js/vendor/jquery.ui.widget.js"
import "script!blueimp-file-upload"
import "script!cloudinary-jquery-file-upload"
```

**Comment by joshlasdin** [comment]
@michaek Of what use is this package in a node environment? I was under the impression that this is a new distribution of the cloudinary client js api's (now jquery-optional). The same packages are available with bower, no? I understand if it doesn't play nice with webpack, but it in general seems to be ill-designed for any client js module bundler, which I would assume is the #1 desired usage of a client package like this.

**Comment by michaek** [comment]
I'm not an author of this code, so I don't know. I just looked at the source, and saw that there are checks like this https://github.com/cloudinary/pkg-cloudinary-jquery-file-upload/blob/master/cloudinary-jquery-file-upload.js#L99 that change the behavior, and those checks are a false positive in webpack.

**Comment by joshlasdin** [comment]
Gotcha, and I definitely appreciate your suggestion. Just frustrated with the lack of response from @cloudinary on this, was excited when they announced they would be distributing their client packages on NPM as well as bower now, but could not find any way to get it to play nice with my module bundler. Having a hard time seeing how this package was designed to be consumed (other than just copying it to a public folder and dropping on the page). Thanks!

**Comment by michaek** [comment]
My example above does work, it just exposes globals.

**Comment by tocker** [comment]
Hi @joshlasdin, @dfguo, @michaek,

Unfortunately we don't support webpack yet.
The package works well with RequireJS (see [test file](https://github.com/cloudinary/cloudinary_js/blob/master/test/docRoot/amd.html)). Looks like some tweaking is required to make it play nice with Webpack.

This library is an [r.js](http://requirejs.org/docs/optimization.html) optimization of the cloudinary_js sources. I wonder if webpack would be able to handle the modules in their [source form](https://github.com/cloudinary/cloudinary_js/tree/master/src).

@joshlasdin the third error you quoted above is from the [Cloudinary NodeJS](https://github.com/cloudinary/cloudinary_npm) library, which expects the NodeJS environment.

I suggest loading the library with a script tag or RequireJS until we have webpack support.

**Comment by joshlasdin** [comment]
@tocker Thank you for the response! I'll continue using workarounds for now.

**Comment by tocker** [comment]
Hi @joshlasdin, @dfguo, @michaek,

webpack now supported in version 2.0.6
Let us know if it works for you!

**Comment by joshlasdin** [comment]
@tocker Just updated, worked great! Thank you!!!
